api/urls.py
from django.urls import path
from api.views import (
    TrainingList,
    SchedduleList,
    peserta_online,
    peserta_offline,
    pendaftar_bulanan,
    peserta_bayar_bulanan,
    interaksi_last_month,
    RegistrationUserList
)

app_name = "api"

urlpatterns = [
    path("trainings/", TrainingList.as_view(), name="TrainingList"),
    path("scheddules/", SchedduleList.as_view(), name="SchedduleList"),
    path("peserta_online/", peserta_online, name="peserta_online"),
    path("peserta_offline/", peserta_offline, name="peserta_offline"),
    path("pendaftar_bulanan/", pendaftar_bulanan, name="pendaftar_bulanan"),
    path("peserta_bayar_bulanan/", peserta_bayar_bulanan, name="peserta_bayar_bulanan"),
    path("interaksi_bulanan/", interaksi_last_month, name="interaksi_bulanan"),
    path("registration_user_list/", RegistrationUserList.as_view(), name="RegistrationUserList"),
]

course/urls.py
from django.urls import path
from course.views import (
    daftar_training,
    delete_registration,
    edit_pendaftaran,
    payment_confirm,
    list_jadwal,
    list_jadwal_online,
    download_contoh_jadwal,
    AddJadwal,
    add_jadwal,
    UpdateJadwal,
    delete_jadwal,
    list_training,
    add_training,
    UpdateTraining,
    delete_training,
    list_pembayaran,
    list_pembayaran_dp_lunas,
    list_pembayaran_ditolak,
    konfirmasi_pembayaran_dp,
    konfirmasi_pembayaran_lunas,
    hapus_konfirmasi,
    tolak_pembayaran,
    list_pendaftar_belum_bayar,
    export_pendaftar_belum_bayar,
    list_peserta,
    list_diskon,
    add_diskon,
    UpdateDiskon,
    delete_diskon,
    upload_jadwal,
    set_max_peserta,
    fu,
    konfirmasi_pembayaran_manual,
)

app_name = "course"

urlpatterns = [
    path("register/", daftar_training, name="daftar_training"),
    path("register/update/<int:pk>/", edit_pendaftaran, name="edit_pendaftaran"),
    path("register/delete/<int:pk>/", delete_registration, name="delete_registration"),
    path(
        "payment_confirm/<int:registration_id>/",
        payment_confirm,
        name="payment_confirm",
    ),
    path("list_jadwal/", list_jadwal, name="list_jadwal"),
    path("list_jadwal_online/", list_jadwal_online, name="list_jadwal_online"),
    path(
        "download_contoh_jadwal/", download_contoh_jadwal, name="download_contoh_jadwal"
    ),
    path("add_jadwal/", add_jadwal, name="add_jadwal"),
    path("update_jadwal/<int:pk>/", UpdateJadwal.as_view(), name="update_jadwal"),
    path("delete_jadwal/<int:pk>/", delete_jadwal, name="delete_jadwal"),
    path("list_training/", list_training, name="list_training"),
    path("add_training/", add_training, name="add_training"),
    path("update_training/<int:pk>/", UpdateTraining.as_view(), name="update_training"),
    path("delete_training/<int:pk>/", delete_training, name="delete_training"),
    path("list_pembayaran/", list_pembayaran, name="list_pembayaran"),
    path(
        "list_pembayaran_dp_lunas/",
        list_pembayaran_dp_lunas,
        name="list_pembayaran_dp_lunas",
    ),
    path(
        "list_pembayaran_ditolak/",
        list_pembayaran_ditolak,
        name="list_pembayaran_ditolak",
    ),
    path(
        "konfirmasi_pembayaran_dp/<int:pk>/",
        konfirmasi_pembayaran_dp,
        name="konfirmasi_pembayaran_dp",
    ),
    path(
        "konfirmasi_pembayaran_lunas/<int:pk>/",
        konfirmasi_pembayaran_lunas,
        name="konfirmasi_pembayaran_lunas",
    ),
    path("hapus_konfirmasi/<int:pk>/", hapus_konfirmasi, name="hapus_konfirmasi"),
    path("tolak_pembayaran/<int:pk>/", tolak_pembayaran, name="tolak_pembayaran"),
    path(
        "list_pendaftar_belum_bayar/",
        list_pendaftar_belum_bayar,
        name="list_pendaftar_belum_bayar",
    ),
    path(
        "export_pendaftar_belum_bayar/",
        export_pendaftar_belum_bayar,
        name="export_pendaftar_belum_bayar",
    ),
    path("list_peserta/<int:pk>/", list_peserta, name="list_peserta"),
    path("list_diskon/", list_diskon, name="list_diskon"),
    path("add_diskon/", add_diskon, name="add_diskon"),
    path("update_diskon/<int:pk>", UpdateDiskon.as_view(), name="update_diskon"),
    path("delete_diskon/<int:pk>", delete_diskon, name="delete_diskon"),
    path("upload_jadwal/", upload_jadwal, name="upload_jadwal"),
    path("set_max_peserta/", set_max_peserta, name="set_max_peserta"),
    path("fu/<int:reg_id>/", fu, name="fu"),
    path("konfirmasi_pembayaran_manual/", konfirmasi_pembayaran_manual, name="konfirmasi_pembayaran_manual")
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("api/", include("api.urls", namespace="api")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("course/", include("course.urls", namespace="course")),
    path("marketing/", include("marketing.urls", namespace="marketing")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models
from django.db.models import Q
from core.models import BaseModel
from accounts.models import User
from course.choices import TrainingType, RegistrationPaymentStatus, Month
from course.utils import upload_bukti_pembayaran


class TrainingCategory(BaseModel):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Training Category"
        verbose_name_plural = "Training Categories"


class Training(BaseModel):
    category = models.ForeignKey(TrainingCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    duration = models.PositiveSmallIntegerField()
    price = models.PositiveIntegerField()
    exclude_diskon = models.BooleanField(default=False)

    class Meta:
        unique_together = ("category", "name", "duration", "price")
        ordering = ["name"]

    def __str__(self):
        return self.name


class MonthYearScheddule(BaseModel):
    month = models.PositiveSmallIntegerField(choices=Month.choices)
    year = models.PositiveSmallIntegerField()

    def __str__(self):
        return f"{Month.choices[self.month-1][1]} {self.year}"

    class Meta:
        verbose_name = "Mont Year Scheddule"


class DayScheddule(BaseModel):
    month_year = models.ForeignKey(MonthYearScheddule, on_delete=models.SET_NULL, null=True, blank=True)
    day = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Day Scheddule"

    def __str__(self):
        return f"{self.day}, {self.month_year}"


class Scheddule(BaseModel):
    training = models.ForeignKey(Training, on_delete=models.CASCADE)
    training_type = models.PositiveSmallIntegerField(choices=TrainingType.choices)
    month_year = models.ForeignKey(MonthYearScheddule, on_delete=models.SET_NULL, null=True, blank=True)
    day = models.ForeignKey(DayScheddule, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("training", "training_type", "month_year", "day")

    def __str__(self):
        return f"{self.day}"

    def get_training_type(self):
        return TrainingType.choices[self.training_type][1]

    def get_jml_peserta(self):
        all_reg = Registration.objects.filter(scheddule=self)
        paid_reg = all_reg.filter(Q(status=2) | Q(status=3))
        return len(paid_reg)


class Registration(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    training_category = models.ForeignKey(TrainingCategory, on_delete=models.CASCADE)
    training_type = models.PositiveSmallIntegerField(choices=TrainingType.choices)
    training = models.ForeignKey(Training, on_delete=models.CASCADE)
    month_year = models.ForeignKey(MonthYearScheddule, on_delete=models.SET_NULL, null=True, blank=True)
    scheddule = models.ForeignKey(Scheddule, on_delete=models.CASCADE)
    status = models.PositiveSmallIntegerField(
        choices=RegistrationPaymentStatus.choices,
        default=RegistrationPaymentStatus.not_paid,
    )
    fu_count = models.IntegerField(default=0)
    last_fu = models.DateTimeField(null=True, blank=True)
    is_retraining = models.BooleanField(default=False)
    diskon_kode = models.CharField(max_length=100, null=True, blank=True)
    affiliate_kode = models.CharField(max_length=100, null=True, blank=True)
    affiliate_point_used = models.IntegerField(null=True, blank=True)

    # this fields is automatically filled by the system
    harga_diskon = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.user} - {self.training}"

    class Meta:
        unique_together = ("user", "training", "training_type")

    def get_status(self):
        return RegistrationPaymentStatus.choices[self.status][1]

    def get_training_type(self):
        return TrainingType.choices[self.scheddule.training_type][1]

    def format_harga_diskon(self):
        if self.harga_diskon is not None:
            return "{:,}".format(self.harga_diskon)
        else:
            return self.harga_diskon

    def get_created_at_month_year(self):
        return f"{Month.choices[self.created_at.month - 1][1]} {self.created_at.year}"


class PaymentConfirm(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    registration = models.ForeignKey(Registration, on_delete=models.CASCADE)
    amount = models.IntegerField()
    proof_of_payment = models.ImageField(upload_to=upload_bukti_pembayaran, null=True, blank=True)
    status = models.PositiveSmallIntegerField(choices=RegistrationPaymentStatus.choices)

    class Meta:
        verbose_name = "Payment Confirm"

    def get_status(self):
        return RegistrationPaymentStatus.choices[self.status][1]

    def get_amount(self):
        return "{:,}".format(self.amount)

    def __str__(self):
        return f"{self.user} - {self.registration.training}"


class Discount(BaseModel):
    persen = models.PositiveIntegerField(null=True, blank=True)
    kode = models.CharField(max_length=100, unique=True)
    end_date = models.DateField()
    training_type = models.PositiveSmallIntegerField(choices=TrainingType.choices)
    diskon_pelajar = models.BooleanField(default=False)

    def __str__(self):
        return self.kode

    def get_training_type(self):
        return TrainingType.choices[self.training_type][1]


class JadwalFile(BaseModel):
    file = models.FileField(upload_to="jadwal_file")


class MaxPeserta(BaseModel):
    max_peserta = models.PositiveIntegerField()


class PointHistory(BaseModel):
    point_used = models.IntegerField()
    registration = models.ForeignKey(Registration, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

course/forms.py
from django import forms
from accounts.models import User
from course.models import Registration
from course.choices import TrainingType
from course.models import (
    TrainingCategory,
    MonthYearScheddule,
    PaymentConfirm,
    Training,
    Scheddule,
    Discount,
    JadwalFile,
    MaxPeserta,
)
from course.utils import max_file_size_2m


class RegistrationFormAdd(forms.ModelForm):
    training_category = forms.ModelChoiceField(
        queryset=TrainingCategory.objects.all(), label="Kategori Training"
    )
    training_type = forms.CharField(
        widget=forms.Select(choices=TrainingType.choices), label="Tipe Training"
    )
    month_year = forms.ModelChoiceField(
        queryset=MonthYearScheddule.objects.all(), label="Bulan"
    )

    class Meta:
        model = Registration
        fields = (
            "training_category",
            "training",
            "training_type",
            "month_year",
            "scheddule",
            "diskon_kode",
            "affiliate_kode",
            "affiliate_point_used",
        )
        labels = {
            "training": "Training",
            "scheddule": "Jadwal",
            "diskon_kode": "Kode Diskon",
            "affiliate_kode": "Kode Affiliate",
            "affiliate_point_used": "Gunakan Affiliate Point",
        }
        widgets = {
            "affiliate_point_used": forms.TextInput(
                attrs={"placeholder": "Contoh: 200"}
            )
        }


class RegistrationFormUpdate(forms.ModelForm):
    class Meta:
        model = Registration
        fields = ("training", "scheddule")


class PaymentConfirmForm(forms.ModelForm):
    proof_of_payment = forms.FileField(
        validators=[max_file_size_2m], label="Bukti Pembayaran (Max 1M)"
    )

    class Meta:
        model = PaymentConfirm
        fields = ("amount", "proof_of_payment")
        labels = {"amount": "Jumlah Transfer", "proof_of_payment": "Bukti Pembayaran"}


class SchedduleForm(forms.ModelForm):
    day_ = forms.CharField(required=False)

    class Meta:
        model = Scheddule
        fields = ("training", "training_type", "month_year", "day_")


class TrainingForm(forms.ModelForm):
    class Meta:
        model = Training
        fields = ("category", "name", "duration", "price", "exclude_diskon")


class DiscountForm(forms.ModelForm):
    class Meta:
        model = Discount
        fields = ("kode", "persen", "end_date", "training_type", "diskon_pelajar")
        widgets = {"end_date": forms.TextInput(attrs={"placeholder": "YYYY-MM-DD"})}


class JadwalFileForm(forms.ModelForm):
    class Meta:
        model = JadwalFile
        fields = ("file",)


class MaxPesertaForm(forms.ModelForm):
    class Meta:
        model = MaxPeserta
        fields = ("max_peserta",)


class PaymentConfirmManual(forms.ModelForm):
    user = forms.ModelChoiceField(User.objects.all().order_by("email"))
    registration = forms.ModelChoiceField(Registration.objects.all().order_by("user__email"))

    class Meta:
        model = PaymentConfirm
        fields = ("user", "registration", "amount")

templates/course/add_jadwal.html
{% extends 'base.html' %}


{% block content %}
    <h3 class="card-title">Add Jadwal</h3>
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Save</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/course/daftar_training.html
{% extends 'base.html' %}
{% load form_tags widget_tweaks %}

{% block content %}
    <h3 class="card-title">Daftar Training</h3>
  <strong style="color: red">Gunakan diskon kode TRAINING_ONLINE jika memilih Training Online untuk mendapatkan diskon 10%</strong>

  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
          {% if form.non_field_errors %}
              <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                  <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
                {% endfor %}
              </div>
          {% endif %}
          {% for field in form %}
            <div class="form-group">
                {% if not field.is_hidden %}
                {{ field.label_tag }}
                {% endif %}
                {% render_field field class=field|input_class %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                {% endfor %}
                {% if field.help_text %}
                    <small class="form-text text-muted">
                        {{ field.help_text }}
                    </small>
                {% endif %}
            </div>
          {% endfor %}
          <br>
        <button type="submit" class="mt-2 btn btn-success">{{ button }}</button>
      </form>
    </div>
  </div>

{% endblock content %}

{% block js %}
<script>

{#Jika training category ganti, list training ganti#}
 $("#id_training_category").change(function () {
    $('#id_training').html("<option value=''>Loading...</option>");
    let category_id = $("#id_training_category").val();
    $.ajax({
        url: "{% url 'api:TrainingList' %}",
        type: "GET",
        data: {category_id:category_id},
        success: function (res, textStatus, jQxhr) {
            console.log(res)
            $('#id_training').html("");
            for (i in res) {
                $('#id_training').append("<option value='" + res[i]['id'] + "'>" + res[i]['name'] + "</option>");
            }
        },
        error: function (jqXhr, textStatus, errorThrown) {
            //console.log(errorThrown);
        }
    });
 });


{#jika training ganti, scheddules ganti#}
$("#id_training").change(function () {
    $('#id_scheddule').html("<option value=''>Loading...</option>");
    let training_id = $("#id_training").val();
    let training_type_id = $("#id_training_type").val();
    let month_year_id = $("#id_month_year").val();
    $.ajax({
        url: "{% url 'api:SchedduleList' %}",
        type: "GET",
        data: {training_id:training_id, training_type_id:training_type_id, month_year_id:month_year_id},
        success: function (res, textStatus, jQxhr) {
            console.log(res)
            $('#id_scheddule').html("");
            for (i in res) {
                $('#id_scheddule').append("<option value='" + res[i]['id'] + "'>" + res[i]['day'] + "</option>");
            }
        },
        error: function (jqXhr, textStatus, errorThrown) {
            //console.log(errorThrown);
        }
    });
});


{# jika training type berubah, scheddule juga berubah #}
$("#id_training_type").change(function () {
    $('#id_scheddule').html("<option value=''>Loading...</option>");
    let training_id = $("#id_training").val();
    let training_type_id = $("#id_training_type").val();
    let month_year_id = $("#id_month_year").val();
    $.ajax({
        url: "{% url 'api:SchedduleList' %}",
        type: "GET",
        data: {training_id:training_id, training_type_id:training_type_id, month_year_id:month_year_id},
        success: function (res, textStatus, jQxhr) {
            console.log(res)
            $('#id_scheddule').html("");
            for (i in res) {
                $('#id_scheddule').append("<option value='" + res[i]['id'] + "'>" + res[i]['day'] + "</option>");
            }
        },
        error: function (jqXhr, textStatus, errorThrown) {
            //console.log(errorThrown);
        }
    });
});


{# jika month year berubah, scheddule juga berubah #}
$("#id_month_year").change(function () {
    $('#id_scheddule').html("<option value=''>Loading...</option>");
    let training_id = $("#id_training").val();
    let training_type_id = $("#id_training_type").val();
    let month_year_id = $("#id_month_year").val();
    $.ajax({
        url: "{% url 'api:SchedduleList' %}",
        type: "GET",
        data: {training_id:training_id, training_type_id:training_type_id, month_year_id:month_year_id},
        success: function (res, textStatus, jQxhr) {
            console.log(res)
            $('#id_scheddule').html("");
            for (i in res) {
                $('#id_scheddule').append("<option value='" + res[i]['id'] + "'>" + res[i]['day'] + "</option>");
            }
        },
        error: function (jqXhr, textStatus, errorThrown) {
            //console.log(errorThrown);
        }
    });
});



</script>

{% endblock js %}

templates/course/list_jadwal.html
{% extends 'base.html' %}
{% block content %}


    <h3>List Jadwal {{ tipe }}</h3>
    <a href="{% url 'course:upload_jadwal' %}">
        <button type="button" class="mt-2 btn btn-primary mb-2">Import Jadwal</button>
    </a>
    <a href="{% url 'course:add_jadwal' %}">
        <button type="button" class="mt-2 btn btn-primary mb-2">Add Jadwal</button>
    </a>
    <table class="table" id="table_id">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nama Training</th>
      <th scope="col">Tipe Training</th>
      <th scope="col">Jadwal</th>
      <th scope="col">Jumlah Peserta</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for s in scheds %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ s.training }}</td>
      <td>{{ s.get_training_type }}</td>
      <td>{{ s.day }}</td>
      <td>{{ s.get_jml_peserta }}</td>
      <td>
          <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Action
          </button>
              <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'course:list_peserta' s.id %}">List Peserta</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'course:update_jadwal' s.id %}">Edit</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#" data-toggle="modal" data-target="#deleteModal-{{ s.id }}">Delete</a>
              </div>
          </div>
        </div>
      </td>

    </tr>

        <!-- Modal -->
        <div class="modal fade" id="deleteModal-{{ s.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                Anda yakin ingin menghapus training {{ s.training }} {{ s.get_training_type }} {{ s.day }}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a href="{% url 'course:delete_jadwal' s.id %}">
                  <button type="button" class="btn btn-danger">Delete</button>
                </a>
              </div>
            </div>
          </div>
        </div>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

templates/course/list_pembayaran.html
{% extends 'base.html' %}
{% block content %}


    <h3>Konfirmasi Pembayaran</h3>
    <a href="{% url 'course:konfirmasi_pembayaran_manual' %}">
        <button type="button" class="mt-2 btn btn-primary mb-2">Konfirmasi Manual</button>
    </a>
    <table class="table" id="table_id">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nama Peserta</th>
      <th scope="col">Email</th>
      <th scope="col">Training</th>
      <th scope="col">Training Type</th>
      <th scope="col">Jadwal</th>
      <th scope="col">Yang harus dibayarkan</th>
      <th scope="col">Jumlah Bayar</th>
      <th scope="col">Bukti Pembayaran</th>
      <th scope="col">No HP</th>
      <th scope="col">Email</th>
      <th scope="col">Alamat</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for pembayaran in list_pembayaran %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ pembayaran.user.profile.name }}</td>
      <td>{{ pembayaran.user.email }}</td>
      <td>{{ pembayaran.registration.training.name }}</td>
      <td>{{ pembayaran.registration.get_training_type }}</td>
      <td>{{ pembayaran.registration.scheddule }}</td>
      <td>{{ pembayaran.registration.format_harga_diskon }}</td>
      <td>{{ pembayaran.get_amount }}</td>
      <td><a target="_blank" {% if pembayaran.proof_of_payment %} href="{{ pembayaran.proof_of_payment.url }}" {% else %} href="#" {% endif %}>Bukti</a> </td>
      <td><a href="{{ pembayaran.user.profile.get_wa_link }}" target="_blank">  {{ pembayaran.user.profile.phone_number }}</a></td>
      <td>{{ pembayaran.user.profile.address }}</td>
      <td>{{ pembayaran.user.email }}</td>

      <td>
          <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Action
          </button>
          <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'course:konfirmasi_pembayaran_dp' pembayaran.id %}">Konfirmasi DP</a>
            <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'course:konfirmasi_pembayaran_lunas' pembayaran.id %}">Konfirmasi Lunas</a>
            <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'course:tolak_pembayaran' pembayaran.id %}">Tolak Pembayaran</a>

          </div>
        </div>
      </td>

    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

templates/course/list_pembayaran_dp_lunas.html
{% extends 'base.html' %}
{% block content %}


    <h3>{{ title }}</h3>
<p><strong>Total Unique Payment: </strong> {{ total_unique_payment }}</p>
    <table class="table" id="table_id">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nama Peserta</th>
      <th scope="col">Email</th>
      <th scope="col">Training</th>
      <th scope="col">Training Type</th>
      <th scope="col">Jadwal</th>
      <th scope="col">Yang harus dibayarkan</th>
      <th scope="col">Jumlah Bayar</th>
      <th scope="col">Bukti Pembayaran</th>
      <th scope="col">No HP</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for pembayaran in list_pembayaran %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ pembayaran.user.profile.name }}</td>
      <td>{{ pembayaran.user.email }}</td>
      <td>{{ pembayaran.registration.training.name }}</td>
      <td>{{ pembayaran.registration.get_training_type }}</td>
      <td>{{ pembayaran.registration.scheddule }}</td>
      <td>{{ pembayaran.registration.format_harga_diskon }}</td>
      <td>{{ pembayaran.get_amount }}</td>
      <td><a target="_blank" href="{% if pembayaran.proof_of_payment %}{{ pembayaran.proof_of_payment.url }}{% endif %}">Bukti</a> </td>
      <td><a href="{{ pembayaran.user.profile.get_wa_link }}" target="_blank">  {{ pembayaran.user.profile.phone_number }}</a></td>

      {% if pembayaran.status == 0 %}
        <td>
        <span class="badge badge-danger">{{ pembayaran.get_status }}</span>
        </td>
        {% elif pembayaran.status == 1 %}
        <td>
        <span class="badge badge-primary">{{ pembayaran.get_status }}</span>
        </td>
        {% elif pembayaran.status == 2 %}
        <td>
        <span class="badge badge-warning">{{ pembayaran.get_status }}</span>
        </td>
        {% elif pembayaran.status == 3 %}
        <td>
        <span class="badge badge-success">{{ pembayaran.get_status }}</span>
        </td>
        {% elif pembayaran.status == 4 %}
        <td>
        <span class="badge badge-dark">{{ pembayaran.get_status }}</span>
        </td>
        {% endif %}

      <td>
          <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Action
          </button>
          <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'course:konfirmasi_pembayaran_dp' pembayaran.id %}">Konfirmasi DP</a>
            <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'course:konfirmasi_pembayaran_lunas' pembayaran.id %}">Konfirmasi Lunas</a>
            <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'course:hapus_konfirmasi' pembayaran.id %}">Hapus Konfirmasi</a>
            <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'course:tolak_pembayaran' pembayaran.id %}">Tolak Pembayaran</a>

          </div>
        </div>
      </td>

    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}