api/urls.py
from django.urls import path
from api.views import (
    TrainingList,
    SchedduleList,
    peserta_online,
    peserta_offline,
    pendaftar_bulanan,
    peserta_bayar_bulanan,
    interaksi_last_month,
    RegistrationUserList
)

app_name = "api"

urlpatterns = [
    path("trainings/", TrainingList.as_view(), name="TrainingList"),
    path("scheddules/", SchedduleList.as_view(), name="SchedduleList"),
    path("peserta_online/", peserta_online, name="peserta_online"),
    path("peserta_offline/", peserta_offline, name="peserta_offline"),
    path("pendaftar_bulanan/", pendaftar_bulanan, name="pendaftar_bulanan"),
    path("peserta_bayar_bulanan/", peserta_bayar_bulanan, name="peserta_bayar_bulanan"),
    path("interaksi_bulanan/", interaksi_last_month, name="interaksi_bulanan"),
    path("registration_user_list/", RegistrationUserList.as_view(), name="RegistrationUserList"),
]

course/urls.py
from django.urls import path
from course.views import (
    daftar_training,
    delete_registration,
    edit_pendaftaran,
    payment_confirm,
    list_jadwal,
    list_jadwal_online,
    download_contoh_jadwal,
    AddJadwal,
    add_jadwal,
    UpdateJadwal,
    delete_jadwal,
    list_training,
    add_training,
    UpdateTraining,
    delete_training,
    list_pembayaran,
    list_pembayaran_dp_lunas,
    list_pembayaran_ditolak,
    konfirmasi_pembayaran_dp,
    konfirmasi_pembayaran_lunas,
    hapus_konfirmasi,
    tolak_pembayaran,
    list_pendaftar_belum_bayar,
    export_pendaftar_belum_bayar,
    list_peserta,
    list_diskon,
    add_diskon,
    UpdateDiskon,
    delete_diskon,
    upload_jadwal,
    set_max_peserta,
    fu,
    konfirmasi_pembayaran_manual,
)

app_name = "course"

urlpatterns = [
    path("register/", daftar_training, name="daftar_training"),
    path("register/update/<int:pk>/", edit_pendaftaran, name="edit_pendaftaran"),
    path("register/delete/<int:pk>/", delete_registration, name="delete_registration"),
    path(
        "payment_confirm/<int:registration_id>/",
        payment_confirm,
        name="payment_confirm",
    ),
    path("list_jadwal/", list_jadwal, name="list_jadwal"),
    path("list_jadwal_online/", list_jadwal_online, name="list_jadwal_online"),
    path(
        "download_contoh_jadwal/", download_contoh_jadwal, name="download_contoh_jadwal"
    ),
    path("add_jadwal/", add_jadwal, name="add_jadwal"),
    path("update_jadwal/<int:pk>/", UpdateJadwal.as_view(), name="update_jadwal"),
    path("delete_jadwal/<int:pk>/", delete_jadwal, name="delete_jadwal"),
    path("list_training/", list_training, name="list_training"),
    path("add_training/", add_training, name="add_training"),
    path("update_training/<int:pk>/", UpdateTraining.as_view(), name="update_training"),
    path("delete_training/<int:pk>/", delete_training, name="delete_training"),
    path("list_pembayaran/", list_pembayaran, name="list_pembayaran"),
    path(
        "list_pembayaran_dp_lunas/",
        list_pembayaran_dp_lunas,
        name="list_pembayaran_dp_lunas",
    ),
    path(
        "list_pembayaran_ditolak/",
        list_pembayaran_ditolak,
        name="list_pembayaran_ditolak",
    ),
    path(
        "konfirmasi_pembayaran_dp/<int:pk>/",
        konfirmasi_pembayaran_dp,
        name="konfirmasi_pembayaran_dp",
    ),
    path(
        "konfirmasi_pembayaran_lunas/<int:pk>/",
        konfirmasi_pembayaran_lunas,
        name="konfirmasi_pembayaran_lunas",
    ),
    path("hapus_konfirmasi/<int:pk>/", hapus_konfirmasi, name="hapus_konfirmasi"),
    path("tolak_pembayaran/<int:pk>/", tolak_pembayaran, name="tolak_pembayaran"),
    path(
        "list_pendaftar_belum_bayar/",
        list_pendaftar_belum_bayar,
        name="list_pendaftar_belum_bayar",
    ),
    path(
        "export_pendaftar_belum_bayar/",
        export_pendaftar_belum_bayar,
        name="export_pendaftar_belum_bayar",
    ),
    path("list_peserta/<int:pk>/", list_peserta, name="list_peserta"),
    path("list_diskon/", list_diskon, name="list_diskon"),
    path("add_diskon/", add_diskon, name="add_diskon"),
    path("update_diskon/<int:pk>", UpdateDiskon.as_view(), name="update_diskon"),
    path("delete_diskon/<int:pk>", delete_diskon, name="delete_diskon"),
    path("upload_jadwal/", upload_jadwal, name="upload_jadwal"),
    path("set_max_peserta/", set_max_peserta, name="set_max_peserta"),
    path("fu/<int:reg_id>/", fu, name="fu"),
    path("konfirmasi_pembayaran_manual/", konfirmasi_pembayaran_manual, name="konfirmasi_pembayaran_manual")
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("api/", include("api.urls", namespace="api")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("course/", include("course.urls", namespace="course")),
    path("marketing/", include("marketing.urls", namespace="marketing")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home.views import home, hi_idn

app_name = "home"

urlpatterns = [
    path("", home, name="home"),
    path("hi_idn/", hi_idn, name="hi_idn"),
]

home/models.py
from django.db import models
from core.models import BaseModel


class HiIDN(BaseModel):
    nama = models.CharField(max_length=100)
    no_hp = models.CharField(max_length=100)
    email = models.EmailField()
    pertanyaan = models.TextField(max_length=255)

    def __str__(self):
        return self.nama

    class Meta:
        verbose_name = "HI IDN"
        verbose_name_plural = "HI IDN"

home/forms.py
from django import forms

from home.models import HiIDN


class HiIDNForms(forms.ModelForm):
    class Meta:
        model = HiIDN
        fields = ("nama", "no_hp", "email", "pertanyaan")


class HiIDNFormsAuthenticated(forms.ModelForm):
    class Meta:
        model = HiIDN
        fields = ("pertanyaan",)

home/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings
from course.models import Registration
from home.forms import HiIDNForms, HiIDNFormsAuthenticated


@login_required
def home(request):
    registrations = Registration.objects.filter(user=request.user).order_by(
        "-created_at"
    )
    context = {"registrations": registrations}
    return render(request, "home/index.html", context)


def hi_idn(request):
    if request.user.is_authenticated and not request.user.profile.is_valid():
        messages.error(
            request,
            "Anda harus melengkap profile Anda sebelum menghubungi admin, <a href='accounts/profile/'>disini</a>",
        )
        return redirect("home:home")

    if request.method == "POST":
        if request.user.is_authenticated:
            form = HiIDNFormsAuthenticated(request.POST)
            if form.is_valid():
                hi = form.save(commit=False)
                hi.nama = request.user.profile.name
                hi.email = request.user.email
                hi.no_hp = request.user.profile.phone_number
                hi.save()

                salam = settings.WA_HI.format(hi.nama).replace(" ", "%20")
                pertanyaan = hi.pertanyaan.replace(" ", "%20")
                url = (
                    settings.WA_URL + settings.WA_ADMIN + "&text=" + salam + pertanyaan
                )
                return redirect(url)

            return render(request, "home/hi_idn_authenticated.html", {"form": form})

        else:
            form = HiIDNForms(request.POST)
            if form.is_valid():
                hi = form.save()

                salam = settings.WA_HI.format(hi.nama).replace(" ", "%20")
                pertanyaan = hi.pertanyaan.replace(" ", "%20")
                url = (
                    settings.WA_URL + settings.WA_ADMIN + "&text=" + salam + pertanyaan
                )
                return redirect(url)

            return render(request, "home/hi_idn.html", {"form": form})

    else:
        if request.user.is_authenticated:
            form = HiIDNFormsAuthenticated()
            return render(request, "home/hi_idn_authenticated.html", {"form": form})
        else:
            form = HiIDNForms()
            return render(request, "home/hi_idn.html", {"form": form})

templates/home/hi_idn.html
{% extends 'accounts/base_account.html' %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Hi IDN</h3>
            <strong style="color: blue">Isi form berikut untuk menghubungi admin via WA</strong>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Kirim</button>
          </form>
        </div>
      </div>
  </div>
  </div>
{% endblock %}

templates/home/hi_idn_authenticated.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="card-title">Hi IDN</h3>
            <strong style="color: blue">Isi form berikut untuk menghubungi admin via WA</strong>
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Kirim</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/home/index.html
{% extends 'base.html' %}
{% block content %}


    {% if user.is_staff %}
        {% include 'home/staff_home.html' %}
    {% else %}
    {% include 'home/users_home.html' %}
    {% endif %}


{% endblock %}

templates/home/staff_home.html
  <div id="container" style="width: 75%;">
    <canvas id="peserta_online" data-url="{% url 'api:peserta_online' %}"></canvas>
    <canvas id="peserta_offline" data-url="{% url 'api:peserta_offline' %}"></canvas>
    <canvas id="pendaftar_bulanan" data-url="{% url 'api:pendaftar_bulanan' %}"></canvas>
    <canvas id="peserta_bayar_bulanan" data-url="{% url 'api:peserta_bayar_bulanan' %}"></canvas>
  </div>

  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    $(function () {

      var $pesertaOnline = $("#peserta_online");
      $.ajax({
        url: $pesertaOnline.data("url"),
        success: function (data) {

          var ctx = $pesertaOnline[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: 'Peserta Online',
                backgroundColor: 'blue',
                data: data.data
              }]          
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Grafik Peserta Online Total'
              }
            }
          });

        }
      });

    });


  $(function () {

      var $pesertaOffline = $("#peserta_offline");
      $.ajax({
        url: $pesertaOffline.data("url"),
        success: function (data) {

          var ctx = $pesertaOffline[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: 'Peserta Offline',
                backgroundColor: 'blue',
                data: data.data
              }]
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Grafik Peserta Offline Total'
              }
            }
          });

        }
      });

    });


  $(function () {

      var $pendaftarBulanan = $("#pendaftar_bulanan");
      $.ajax({
        url: $pendaftarBulanan.data("url"),
        success: function (data) {

          var ctx = $pendaftarBulanan[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: 'Pendaftar',
                backgroundColor: 'blue',
                data: data.data
              }]
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Grafik Pendaftar Bulanan'
              }
            }
          });

        }
      });

    });





  $(function () {

      var $pesertaBayarBulanan = $("#peserta_bayar_bulanan");
      $.ajax({
        url: $pesertaBayarBulanan.data("url"),
        success: function (data) {

          var ctx = $pesertaBayarBulanan[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: 'Pendaftar Bayar',
                backgroundColor: 'blue',
                data: data.data
              }]
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Grafik Pendaftar Bayar Bulanan'
              }
            }
          });

        }
      });

    });

  </script>

templates/home/users_home.html
<h3>History Training</h3>
    <a href="{% url 'course:daftar_training' %}">
        <button type="button" class="mt-2 btn btn-primary mb-2">Daftar Training</button>
    </a>
    <table class="table" id="table_id">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nama Training</th>
      <th scope="col">Tipe Training</th>
      <th scope="col">Jadwal</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for reg in registrations %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ reg.training }}</td>
      <td>{{ reg.get_training_type }}</td>
      <td>{{ reg.scheddule }}</td>
        {% if reg.status == 0 %}
        <td>
        <span class="badge badge-danger">{{ reg.get_status }}</span>
        </td>
        {% elif reg.status == 1 %}
        <td>
        <span class="badge badge-primary">{{ reg.get_status }}</span>
        </td>
        {% elif reg.status == 2 %}
        <td>
        <span class="badge badge-warning">{{ reg.get_status }}</span>
        </td>
        {% elif reg.status == 3 %}
        <td>
        <span class="badge badge-success">{{ reg.get_status }}</span>
        </td>
        {% elif reg.status == 4 %}
        <td>
        <span class="badge badge-dark">{{ reg.get_status }}</span>
        </td>
        {% endif %}
      <td>
            {% if reg.status == 0 or reg.status == 4 or reg.status == 2 %}

          <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Action
          </button>
          <div class="dropdown-menu">
{#              <a class="dropdown-item" href="{% url 'course:edit_pendaftaran' reg.id %}">Edit</a>#}
              <a class="dropdown-item" href="{% url 'course:payment_confirm' reg.id %}">Konfirmasi Pembayaran</a>
            <div class="dropdown-divider"></div>
              {% if reg.status == 0 or reg.status == 4 %}
                 <a class="dropdown-item" href="#" data-toggle="modal" data-target="#deleteModal-{{ reg.id }}">Delete</a>
              {% endif %}
          </div>
        </div>
            {% else %}
                <button disabled type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Action
              </button>
            {% endif %}

      </td>

    </tr>

        <!-- Modal -->
        <div class="modal fade" id="deleteModal-{{ reg.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                Anda yakin ingin menghapus training {{ reg.training }}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a href="{% url 'course:delete_registration' reg.id %}">
                  <button type="button" class="btn btn-danger">Delete</button>
                </a>
              </div>
            </div>
          </div>
        </div>
    {% endfor %}
  </tbody>
</table>