accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeView,
    PasswordChangeDoneView,
)
from accounts.views import signup, activate_account, profile, affiliate_view
from dashboard import settings

app_name = "accounts"

urlpatterns = [
    path("signup/", signup, name="signup"),
    path("signup/<str:token>/", activate_account, name="activate_account"),
    path(
        "login/", LoginView.as_view(template_name="accounts/login.html"), name="login"
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "settings/password/",
        PasswordChangeView.as_view(
            template_name="accounts/password_change.html",
            success_url=reverse_lazy("accounts:password_change_done"),
        ),
        name="password_change",
    ),
    path(
        "settings/password/done/",
        PasswordChangeDoneView.as_view(
            template_name="accounts/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "reset/",
        PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
            html_email_template_name="accounts/password_reset_email.html",
            email_template_name="accounts/password_reset_email.html",
            subject_template_name="accounts/password_reset_subject.txt",
            success_url=reverse_lazy("accounts:password_reset_done"),
            from_email=f"Info IDN.ID <{settings.EMAIL_FORM}>",
        ),
        name="password_reset",
    ),
    path(
        "reset/done/",
        PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<str:uidb64>/<str:token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("profile/", profile, name="profile"),
    path("affiliate/", affiliate_view, name="affiliate"),
]

api/urls.py
from django.urls import path
from api.views import (
    TrainingList,
    SchedduleList,
    peserta_online,
    peserta_offline,
    pendaftar_bulanan,
    peserta_bayar_bulanan,
    interaksi_last_month,
    RegistrationUserList
)

app_name = "api"

urlpatterns = [
    path("trainings/", TrainingList.as_view(), name="TrainingList"),
    path("scheddules/", SchedduleList.as_view(), name="SchedduleList"),
    path("peserta_online/", peserta_online, name="peserta_online"),
    path("peserta_offline/", peserta_offline, name="peserta_offline"),
    path("pendaftar_bulanan/", pendaftar_bulanan, name="pendaftar_bulanan"),
    path("peserta_bayar_bulanan/", peserta_bayar_bulanan, name="peserta_bayar_bulanan"),
    path("interaksi_bulanan/", interaksi_last_month, name="interaksi_bulanan"),
    path("registration_user_list/", RegistrationUserList.as_view(), name="RegistrationUserList"),
]

course/urls.py
from django.urls import path
from course.views import (
    daftar_training,
    delete_registration,
    edit_pendaftaran,
    payment_confirm,
    list_jadwal,
    list_jadwal_online,
    download_contoh_jadwal,
    AddJadwal,
    add_jadwal,
    UpdateJadwal,
    delete_jadwal,
    list_training,
    add_training,
    UpdateTraining,
    delete_training,
    list_pembayaran,
    list_pembayaran_dp_lunas,
    list_pembayaran_ditolak,
    konfirmasi_pembayaran_dp,
    konfirmasi_pembayaran_lunas,
    hapus_konfirmasi,
    tolak_pembayaran,
    list_pendaftar_belum_bayar,
    export_pendaftar_belum_bayar,
    list_peserta,
    list_diskon,
    add_diskon,
    UpdateDiskon,
    delete_diskon,
    upload_jadwal,
    set_max_peserta,
    fu,
    konfirmasi_pembayaran_manual,
)

app_name = "course"

urlpatterns = [
    path("register/", daftar_training, name="daftar_training"),
    path("register/update/<int:pk>/", edit_pendaftaran, name="edit_pendaftaran"),
    path("register/delete/<int:pk>/", delete_registration, name="delete_registration"),
    path(
        "payment_confirm/<int:registration_id>/",
        payment_confirm,
        name="payment_confirm",
    ),
    path("list_jadwal/", list_jadwal, name="list_jadwal"),
    path("list_jadwal_online/", list_jadwal_online, name="list_jadwal_online"),
    path(
        "download_contoh_jadwal/", download_contoh_jadwal, name="download_contoh_jadwal"
    ),
    path("add_jadwal/", add_jadwal, name="add_jadwal"),
    path("update_jadwal/<int:pk>/", UpdateJadwal.as_view(), name="update_jadwal"),
    path("delete_jadwal/<int:pk>/", delete_jadwal, name="delete_jadwal"),
    path("list_training/", list_training, name="list_training"),
    path("add_training/", add_training, name="add_training"),
    path("update_training/<int:pk>/", UpdateTraining.as_view(), name="update_training"),
    path("delete_training/<int:pk>/", delete_training, name="delete_training"),
    path("list_pembayaran/", list_pembayaran, name="list_pembayaran"),
    path(
        "list_pembayaran_dp_lunas/",
        list_pembayaran_dp_lunas,
        name="list_pembayaran_dp_lunas",
    ),
    path(
        "list_pembayaran_ditolak/",
        list_pembayaran_ditolak,
        name="list_pembayaran_ditolak",
    ),
    path(
        "konfirmasi_pembayaran_dp/<int:pk>/",
        konfirmasi_pembayaran_dp,
        name="konfirmasi_pembayaran_dp",
    ),
    path(
        "konfirmasi_pembayaran_lunas/<int:pk>/",
        konfirmasi_pembayaran_lunas,
        name="konfirmasi_pembayaran_lunas",
    ),
    path("hapus_konfirmasi/<int:pk>/", hapus_konfirmasi, name="hapus_konfirmasi"),
    path("tolak_pembayaran/<int:pk>/", tolak_pembayaran, name="tolak_pembayaran"),
    path(
        "list_pendaftar_belum_bayar/",
        list_pendaftar_belum_bayar,
        name="list_pendaftar_belum_bayar",
    ),
    path(
        "export_pendaftar_belum_bayar/",
        export_pendaftar_belum_bayar,
        name="export_pendaftar_belum_bayar",
    ),
    path("list_peserta/<int:pk>/", list_peserta, name="list_peserta"),
    path("list_diskon/", list_diskon, name="list_diskon"),
    path("add_diskon/", add_diskon, name="add_diskon"),
    path("update_diskon/<int:pk>", UpdateDiskon.as_view(), name="update_diskon"),
    path("delete_diskon/<int:pk>", delete_diskon, name="delete_diskon"),
    path("upload_jadwal/", upload_jadwal, name="upload_jadwal"),
    path("set_max_peserta/", set_max_peserta, name="set_max_peserta"),
    path("fu/<int:reg_id>/", fu, name="fu"),
    path("konfirmasi_pembayaran_manual/", konfirmasi_pembayaran_manual, name="konfirmasi_pembayaran_manual")
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("api/", include("api.urls", namespace="api")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("course/", include("course.urls", namespace="course")),
    path("marketing/", include("marketing.urls", namespace="marketing")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home.views import home, hi_idn

app_name = "home"

urlpatterns = [
    path("", home, name="home"),
    path("hi_idn/", hi_idn, name="hi_idn"),
]

marketing/urls.py
from django.urls import path
from marketing.views import (
    InteraksiListView,
    createInteraksi,
    editInteraksi,
    delete_interaksi,
    interaksi_bulanan,
)

app_name = "marketing"

urlpatterns = [
    path("list_interaksi/", InteraksiListView.as_view(), name="list_interaksi"),
    path("add_interaksi/", createInteraksi, name="add_interaksi"),
    path("edit_interaksi/<int:pk>/", editInteraksi, name="edit_interaksi"),
    path("delete_interaksi/<int:pk>/", delete_interaksi, name="delete_interaksi"),
    path("interaksi_bulanan/", interaksi_bulanan, name="interaksi_bulanan"),
]

templates/includes/form.html
{% load form_tags widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}


{% for field in form %}
    <div class="form-group">
        {% if not field.is_hidden %}
        {{ field.label_tag }}
        {% endif %}
        {% render_field field class=field|input_class %}
        {% for error in field.errors %}
            <div class="invalid-feedback">
                {{ error }}
            </div>
        {% endfor %}
        {% if field.help_text %}
            <small class="form-text text-muted">
                {{ field.help_text }}
            </small>
        {% endif %}
    </div>
{% endfor %}

templates/includes/sidebar_admin.html
<!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:affiliate' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>Affiliate</span></a>
      </li>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsetraining" aria-expanded="true" aria-controls="collapsetraining">
          <i class="fas fa-fw fa-cog"></i>
          <span>Training</span>
        </a>
        <div id="collapsetraining" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'course:list_jadwal' %}">List Jadwal Offline</a>
            <a class="collapse-item" href="{% url 'course:list_jadwal_online' %}">List Jadwal Online</a>
            <a class="collapse-item" href="{% url 'course:list_training' %}">List Training</a>
            <a class="collapse-item" href="{% url 'course:list_diskon' %}">List Diskon</a>

          </div>
        </div>
      </li>



      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-cog"></i>
          <span>Pembayaran</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'course:list_pembayaran' %}">Konfirmasi Pembayaran</a>
            <a class="collapse-item" href="{% url 'course:list_pembayaran_dp_lunas' %}">Pembayaran DP / Lunas</a>
            <a class="collapse-item" href="{% url 'course:list_pembayaran_ditolak' %}">Pembayaran Ditolak</a>
            <a class="collapse-item" href="{% url 'course:list_pendaftar_belum_bayar' %}">Belum Bayar</a>

          </div>
        </div>
      </li>


      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsemarketing" aria-expanded="true" aria-controls="collapsemarketing">
          <i class="fas fa-fw fa-cog"></i>
          <span>Marketing</span>
        </a>
        <div id="collapsemarketing" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'marketing:interaksi_bulanan' %}">Grafik Interaksi</a>
            <a class="collapse-item" href="{% url 'marketing:list_interaksi' %}">List Interaksi</a>

          </div>
        </div>
      </li>



      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
          <i class="fas fa-fw fa-cog"></i>
          <span>Settings</span>
        </a>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="{% url 'course:set_max_peserta' %}">Konfigurasi Max Peserta</a>

          </div>
        </div>
      </li>


      <!-- Divider -->
      <hr class="sidebar-divider">

templates/includes/sidebar_user.html
<!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>


      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" target="_blank" href="https://www.idn.id/jadwal/">
          <i class="fas fa-fw fa-table"></i>
          <span>Jadwal Offline</span></a>
      </li>



      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" target="_blank" href="https://www.idn.id/online/">
          <i class="fas fa-fw fa-table"></i>
          <span>Jadwal Online</span></a>
      </li>



      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:hi_idn' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>Hi IDN</span></a>
      </li>


      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:affiliate' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>Affiliate</span></a>
      </li>


      <!-- Divider -->
      <hr class="sidebar-divider">